require 'spree_core'
require 'spree_api'
require 'spree_active_model_serializer/spree_ams'
require 'spree_active_model_serializer/serializable'
require 'spree_active_model_serializer/requestable'
require 'spree_active_model_serializer/engine'
